language: python
sudo: true
addons:
    postgresql: "9.6"

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.9-dev"
    - python: "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U pip
  - pip install wheel
  - pip install sqlalchemy $SQLPYCLIENT
  - pip install -U flake8 coverage pytest pytest-cov
  - pip install anyblok_marshmallow
  - pip install coveralls
  - pip install -U coveralls
  - pip install .

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok --exclude=*/tests/*
  - psql -c 'create database travis_ci_test;' -U postgres
  - pytest --cov-report= --cov=anyblok_mixins anyblok_mixins/tests
  
after_success:
  coveralls --data_file=.coverage --config_file=.coveragerc
